# Generated by Django 3.2.9 on 2021-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(blank=True, db_column='nome', help_text='Nome do Usuário', max_length=30)),
                ('sobrenome_usuario', models.CharField(db_column='sobrenome', help_text='Sobrenome do usuário', max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], db_column='sexo', default='Masculino', max_length=1)),
                ('telefone_usuario', models.CharField(db_column='telefone', max_length=30)),
                ('data_de_nascimento', models.DateField(db_column='dataNascimento')),
                ('email_usuario', models.EmailField(db_column='email', help_text='Email do usuário', max_length=254, unique=True)),
                ('senha_usuario', models.CharField(db_column='senha', max_length=30)),
                ('receber_newsletter', models.BooleanField(db_column='newsletter')),
                ('comentarios', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Usuario',
            },
        ),
    ]
